name : CI - Emotion Dary (.NET)

on: 
  push:
    branches: [main]
    paths:
      - "Emotion_dairy_dotnet/**"
      - ".github/workflows/emotion-diary-donet-ci.yml"
      - ".github/workflows/node-ci.yml"
  pull_request:
    paths: 
      - "Emotion_dary_dotnet/**"
      - ".github/workfolows/emotion-diary-dotnet-ci.yml"
      - ".github/workflows/node-ci.yml"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Emotion_diary_dotnet/backend
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  frontend:
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: Emotion_diary_dotnet/frontend
      lint: false
      test: false
      